language: node_js

node_js:
  - "0.12"

before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_a776e53ebab8_key -iv $encrypted_a776e53ebab8_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  # Set the permission of the key
  - chmod 600 ~/.ssh/id_rsa
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "Pei.Pan"
  - git config --global user.email pannpei@gmail.com
  # Install Hexo
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo generate
  - hexo deploy

branches:
  only:
    - master